### PR TITLE
Adding check_all() function

### PR DESCRIPTION
**Pull request by csgillespie**
* Add check_all function
 * Allow all checks to run before raising an error

### CODE REVIEW

**Review by jwalton3141 — APPROVED** [review]
Looks good.

I see that `check_rpoj()` could still raise a premature call to `stop()` (via `get_rproj()`), but that we don't use the `check_rproj()` test in `check_all()`.

**Comment by csgillespie** [comment]
`check_rproj()` should be there!

**Comment by csgillespie** [comment]
@jwalton3141 Add the check_rproj to check_all()

I also decided that check_rproj should raise an error if an .Rproj is missing (otherwise why would you run the check)

**Comment by jwalton3141** [comment]
looks good. @csgillespie can we merge?

**Pull request merged**
